### PR TITLE
Sendgrid: Support Mail Body Compression

### PR DESCRIPTION
**Pull request by luhagel**
Heya,
Sendgrid supports sending in gzip compressed bodies. (see [here](https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send#mail-body-compression))

This PR adds an option for that to the Adapter.

I'm somewhat unsure how to properly test this without duplicating most of the existing testsuite, so any pointers would be welcome here :)

Also, if there is a less invasive way to set the headers/compress the body I'm happy to make adjustments as needed.

### CODE REVIEW

**Comment by princemaple** [comment]
Since `bypass` is a proper plug server, I think we can simply test if the header is expected, and the content is correctly parsed by the server, when compress is set to `true`. We don't need to test every scenario in a compressed setting.

**Comment by luhagel** [comment]
Gonna need some more time with this, we'll need a custom Plug Parser for, should find some time the next few days 👍

**Comment by kevinam99** [comment]
@luhagel - are you still working on this? I have some bandwidth and I think I can help. I'll appreciate any earlier context you have on this :)

**Comment by luhagel** [comment]
@kevinam99 Heya, 
planning to over the holidays - the last few weeks were pretty rough work-wise ^^

I'll gladly accept any help you can spare :)

**Comment by kevinam99** [comment]
@luhagel okay cool, let me take a shot at this

**Comment by kevinam99** [comment]
Okay, I think I have something here. Noticed a weird behaviour with the parsers https://github.com/luhagel/swoosh/pull/1

Had to add a check for the gzip parser in conn_parser based on the content-encoding header because when I used it in the regular list of parsers, the `parse` callback wouldn't get invoked at all leading the test to fail. If I add the Gzip parser at the top of the list, only this one test would pass

**Comment by kevinam99** [comment]
Never mind. Managed to fix the problem :)

**Comment by princemaple** [comment]
Hi all, turned out that a custom parser wasn't the correct way to go. I changed it to use a custom body reader. I think we are all good now.

**Comment by princemaple** [comment]
Thank you both!

**Pull request merged**
