### PR TITLE
Update README for 

### PR DESCRIPTION
**Pull request by Shmink**
Adapter table not being displayed correctly in hexdocs, even though it's fine in the GH repo README.

screen shot 2018-10-11 at 10 30 16

Should now be fixed.

### CODE REVIEW

**Comment by princemaple** [comment]
@Shmink Thanks!

**Comment by princemaple** [comment]
Docs update has been published to hex.

**Comment by princemaple** [comment]
Yep 🎉  thank you!

**Comment by stevedomin** [comment]
Thanks @Shmink, been wanting to do that for a while!

**Pull request merged**
