### PR TITLE
deliver_many/2 callback and implementation for Mailjet

### PR DESCRIPTION
**Pull request by panmichal**
As discussed in https://github.com/swoosh/swoosh/issues/436

Return values for `deliver/2` are left unchanged, for both success response and errors.
In `deliver/2` messages was a one-element list and I've made it a bit more generic so most of the logic is shared between those 2 functions.

### CODE REVIEW

**Comment by princemaple** [comment]
Thanks for the PR! Will review it tomorrow or over the weekend.

**Comment by princemaple** [comment]
Hi @panmichal please take a look at my changes. Thanks.

FYI there seems to be some change with Travis CI and I couldn't restart the build. I've re-pushed it in #442 . If everything is good I might have to close this and merge #442.

**Comment by panmichal** [comment]
Hi @princemaple looks better now :) And still works, so 👍

**Comment by princemaple** [comment]
closing in favor of #442

**Pull request closed without merging**
