### PR TITLE
Return email body from Sendgrid adapter when emails are sent successfully

### PR DESCRIPTION
**Pull request by sadir**
Fixes https://github.com/swoosh/swoosh/issues/455.

Going to turn the raw response body into a map, let me know now if you don't want to do that?

Also, I've got two other commits that you may or may not want. 

We use [asdf](https://github.com/asdf-vm/asdf) to manage versions per-project at Nested, thought you may want to consider using that to make development onboarding easier.

We mix format every file at Nested to remove debate about styling, spaces and indentation, etc. You may want to consider using that to make development onboarding easier.

Entirely up to you on these! I'm happy to accept your guidance.

### CODE REVIEW

**Comment by sadir** [comment]
Looks like you have the [Plug.Parsers.JSON](https://hexdocs.pm/plug/Plug.Parsers.JSON.html) in use, so maybe the test data is wrong? It should already be a map?

**Comment by princemaple** [comment]
Hi @sadir thanks for the quick PR. I'm in AEST so it's about mid night now. I'll review this and get back to you over the weekend or next week. Stay safe and have a good one!

**Comment by princemaple** [comment]
Hi @sadir , running the formatter over the files you worked with is great. I did format many files along the way. I just didn't do it over the whole project. A separate PR to do that is welcome as well!

`.tool-version` I'm not sure. I use Windows and asdf doesn't work here. Also, I'm always on latest Elixir (1.10+) and OTP (22.3 now). I think it may not be wanted for everyone. I think it's more useful in company projects than in libraries.

Regarding the tests, you might want to replace `respond_with` with something like `Plug.Conn.resp(conn, 200, success_response)`, that might make a difference.

I'm OK with parsing response body, as long as the service provider documents that they return json response on successful requests. Please make a note in the adapter moduledoc as well.

Thanks again for the PR!

**Comment by sadir** [comment]
Right - should all be there for you now. I've made it ready for review!

**Pull request merged**
