### PR TITLE
fix clear button path when base_path is set

### PR DESCRIPTION
**Pull request by jhchen**
Thanks for this library! The latest version added a clear button but it will not work if you have `base_path` set as we do in our use. This PR takes this option into account and constructs the urls accordingly.

### CODE REVIEW

**Comment by princemaple** [comment]
Hi @jhchen , could you check if it still works with the commit I added? Thanks!

**Comment by jhchen** [comment]
Yup still works for me! Thanks didn't know if I should change the default base_path but this makes it cleaner.

**Comment by princemaple** [comment]
Thanks for the confirmation!

**Comment by princemaple** [comment]
It's out in v0.16.1

**Pull request merged**
