### PR TITLE
Add Cowboy2

### PR DESCRIPTION
**Pull request by hl**
I'd like to add cowboy 2 to the mix.

The current version (2.4) still has `Plug.Adapters.Cowboy` and the mail preview works.

### CODE REVIEW

**Comment by princemaple** [comment]
Thanks. Could you include the mix.lock change as well?

**Comment by stevedomin** [comment]
@princemaple do you think we should do that yet?

**Comment by princemaple** [comment]
`{:cowboy, "~> 1.0.1 or ~> 1.1 or ~> 2.4", optional: true},` I don't see anything harmful. Users can still choose which version to use..?

**Comment by stevedomin** [comment]
True! 👍

**Comment by princemaple** [comment]
Just tried locally, you are right.

**Pull request merged**
