### PR TITLE
Add option to change encoding to smtp adapter

### PR DESCRIPTION
**Pull request by ivan-kolmychek**
Ref #340.

This was born as a "quick and dirty" fix, so it may not be perfect. 
Tests are passing, but I have not added any new ones. 
It also does not solve the original issue itself, just side-steps it with using different encoding.

Feedback and advice on how to improve it (and what tests to add) are welcome.

### CODE REVIEW

**Comment by ivan-kolmychek** [comment]
@princemaple thanks. Of course, take your time. 

We are using this in the meantime as fork, so maybe we'll spot any other nuances as well.

**Comment by princemaple** [comment]
Hi @ivan-kolmychek , how's your change been going for you? I made a few modifications. I'll merge this one in if there hasn't been any issue on your side.

**Comment by ivan-kolmychek** [comment]
@princemaple it's running all right, we have not found any issues so far.

I pulled your changes and tested it a bit locally now, it does works for me.

After you will merge I think we can switch to using `master` for now, so it will get more live testing until you are ready to actually release next version.

**Comment by princemaple** [comment]
Thanks a lot for testing this live :)

**Comment by princemaple** [comment]
Hi @ivan-kolmychek , just checking, has master caused any trouble so far?

**Comment by ivan-kolmychek** [comment]
@princemaple no, have not spotted any problems yet, but we pinned it to the [merge commit](https://github.com/swoosh/swoosh/commit/4f2196ca73e061329b1e493f9d12dc5aeb1c5f07) for now, so I can't say anything about any further changes.
We can swap it to current HEAD on Monday (Feb 18th) to test that through a bit more.

**Comment by princemaple** [comment]
Thanks for the reply. The later commits should not have an impact on the SMTP code. I think I will make a release sometime next week. Thanks again!

**Pull request merged**
