### PR TITLE
Raise an error if the mailgun config is missing :domain or :api_key

### PR DESCRIPTION
**Pull request by monicao**
References: https://github.com/swoosh/swoosh/issues/76

Let me know if you have any comments. Thanks.

### CODE REVIEW

**Comment by stevedomin** [comment]
I was thinking of adding that back yesterday, so this PR is definitely timely.

Couple of comments:
- I'm not a fan of the `if` statement in deliver/2, it would be nicer to extract the check to a separate function and use it from the Mailer.
- I'm not sure we should `raise` here, maybe we could just return a `{:error, reason}` tuple. @barisbalic what do you think?
- We will need to add this feature to other adapters as well, I can tackle that separately.

Sorry it's quite a lot of comments, let us know if you need any help on this @monicao

**Comment by monicao** [comment]
@stevedomin Thanks for the detailed feedback.

I moved the config validation to `Swoosh.Mailer`. Every adapter can implement a `required_config_keys` function that returns a list of config key names. 

The idea is that each adapter would implement this function and it could be added to the `Swoosh.Adapter` behaviour. Right now I added a function that ignores adapters that do not implement the function. 

Let me know what you think. I am pretty new to elixir so I am still learning the style conventions and best practices.

**Comment by stevedomin** [comment]
@monicao reading your code and having thought more about it I think it could be even simpler (and more flexible). Let's just have a `validate_config` function in each of the adapter (you can leave it as a noop in all the adapters that you don't care about) and add it to the `Swoosh.Adapter` behaviour.

There are a couple of benefits:
- Each adapter is responsible for implementing its own logic, and can do more than checking for required keys.
- It's easier to give more specific error message, eg. "this particular key is missing", rather than "all these keys are required"
- The logic in `Swoosh.Mailer` is much simpler.

I'd still like to hear from @barisbalic (and maybe @lau as well) on the tuple vs raise issue. It would be nice to validate the config when the app starts but since you can pass additional config when calling `deliver/2` we'd have to validate it at each call anyway.

Let me know if you're still keen on working on that, I'm going to be around now so you will have a faster feedback loop.

**Comment by barisbalic** [comment]
Hey all!

I think with regards to the implementation it makes sense for each adapter to house it's own checks.  As for raising.  I am leaning toward returning a tuple of `{:error, "reason"}`, for the reasons @stevedomin stated.

**Comment by monicao** [comment]
@stevedomin @barisbalic Sounds good. I can make the changes.

**Comment by monicao** [comment]
@stevedomin Updated the code and added validations for the Mailgun and SMTP adapters.

**Comment by stevedomin** [comment]
Thanks @monicao, it looks great.

For some reasons CI didn't pick your last commit, can you try rebasing against master, squashing your commits and pushing again?

**Comment by monicao** [comment]
@stevedomin Here it is. Looks like I missed something in the LoggerAdapter, but all the tests are passing now.

**Comment by barisbalic** [comment]
Hi @monicao sorry for taking so long to get back to this!  Could you rebase against master and I'll get this merged in for you.

**Comment by monicao** [comment]
@barisbalic I'm having trouble doing the rebase against master. I think the commits I squashed earlier are back... sigh. If you have time could you give me a hand with the rebase? I added you as a collaborator to the fork.
Otherwise I can create a new fork and make the changes manually.

**Comment by monicao** [comment]
@barisbalic OK, figured out the rebase. Changes from master have been pulled in.

**Comment by barisbalic** [comment]
@monicao thanks for granting me access, if I had had a moment I would have tried to help :(

We really appreciate both your contribution, and your patience, thanks again!

**Comment by monicao** [comment]
Thanks guys! This was fun :)

**Pull request merged**
