### PR TITLE
Mailjet

### PR DESCRIPTION
**Pull request by princemaple**
Close #259

### CODE REVIEW

**Comment by princemaple** [comment]
@panmichal thanks a lot for taking this one forward. I'll review it as a whole soon.

**Comment by panmichal** [comment]
Hmm, okay, test should use `Swoosh.AdapterCase` instead of `AdapterCase`, looks like it has changed on master.

**Comment by princemaple** [comment]
Thanks. That's correct.

**Comment by princemaple** [comment]
@panmichal @denispeplin Thanks a lot for your contributions!

**Comment by augnustin** [comment]
Hey guys!

Great to read that the Mailjet adapter is here! :smile: 

The doc hasn't been updated though, this could certainly help.

But at first, is it possible print out a usage example here? It may not be difficult but I'm slightly confused, especially regarding where to set the template_id!

Cheers!

**Comment by panmichal** [comment]
@augnustin you can use `put_provider_option(:template_id, your_template_id)`.

Good catch with the docs, I'll try to fix it.

**Pull request merged**
