### PR TITLE
Socketlabs adapter

### PR DESCRIPTION
**Pull request by mpran**
Adapter for SocketLabs Injection API

### CODE REVIEW

**Comment by princemaple** [comment]
Hi @mpran, thanks for the PR. Looks good on first scan. I'll take another look, probably make some small changes and merge soon.

**Comment by princemaple** [comment]
A few things I thought I would change seem OK on second pass. Thanks again @mpran for the PR!

**Comment by princemaple** [comment]
Would you like to send another PR to update readme?

**Comment by mpran** [comment]
@princemaple yup I will get another PR to update  readme. Thanks!

**Comment by princemaple** [comment]
Great, cheers!

**Pull request merged**
