### PR TITLE
Add mail_settings to enable sandbox_mode for sendgrid adapter

### PR DESCRIPTION
**Pull request by rhnonose**
Implements #286

### CODE REVIEW

**Comment by princemaple** [comment]
Looks good, thanks!

**Comment by princemaple** [comment]
Would you be able to add some documentation for this feature too?

**Comment by rhnonose** [comment]
Couldn't find a place to put it, should it be in `lib/swoosh/adapters/sendgrid.ex` or `lib/swoosh/email.ex`?

**Comment by princemaple** [comment]
In the module doc of sendgrid.ex will be great!

**Pull request merged**
