### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by princemaple**
need *squash merge*

### CODE REVIEW

**Comment by princemaple** [comment]
@stevedomin ready for v0.13?

**Comment by jann** [comment]
👍  for v0.13

**Comment by jann** [comment]
hi @princemaple @stevedomin are you planing on releasing a new version anytime soon? We would love to use master branch for dyn email provider.

**Comment by princemaple** [comment]
@jann I don't have release access. You will have to wait for Steve to be available.

**Comment by stevedomin** [comment]
@jann doing that today! I'm also going to enable @princemaple to do releases so we can move faster.

Apologies for the wait!

**Comment by stevedomin** [comment]
@jann 0.13 is out, with the Dyn adapter! Sorry again for the wait.

**Comment by jann** [comment]
thank you, no problem at all.

**Pull request merged**
