### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by princemaple**

### CODE REVIEW

**Comment by princemaple** [comment]
Hold until next big release, or when OTP20 is released, whichever comes first.

**Comment by stevedomin** [comment]
👍 (can you rebase against master and squash your commits that way it's done for whenever OTP20 comes out)

**Comment by stevedomin** [comment]
@princemaple OTP20 is out!

**Comment by princemaple** [comment]
looks like travis is lacking otp 20 support still, https://github.com/travis-ci/travis-ci/issues/7947

**Comment by stevedomin** [comment]
👍

**Comment by goncalotomas** [comment]
@princemaple Travis has Erlang 20 RC1 available if you use `20.0-rc1` temporarily.

**Pull request merged**
