### PR TITLE
Add sendinblue adapter

### PR DESCRIPTION
**Pull request by tofran**
DRAFT

This PR adds an adapter for sendinblue (transactional emails only).
Related to #537

Todo:

- [x] solve the mandatory `from` problem
- [x] add attachments support
- [x] update documentation to include the new adapter
- [x] fix ` when name in [nil, ""] and not is_map_key(body, :to)`
- [x] Add tests

@princemaple Can you help here?

### CODE REVIEW

**Comment by princemaple** [comment]
Does sendinblue not support attachments?

**Comment by tofran** [comment]
@princemaple

Yes [it does](https://developers.sendinblue.com/reference#sendtransacemail), I have just added it 0862865 

PR summary updated

**Comment by princemaple** [comment]
I'll get to the `from` issue sometime during the next week. If you can work on the tests in the meantime, it would be great. Thanks for the PR and quick response.

**Comment by tofran** [comment]
Thank you!
Yes I'll try my best.

Regarding the `form`: Why not remove it entirely from the generic validation and give responsibility to the adapters?

**Comment by princemaple** [comment]
Easier to maintain one check than every single adapter

**Comment by princemaple** [comment]
> see why when name in [nil, ""] and not is_map_key(body, :to) fails
`is_map_key` was introduced in Elixir 1.10

**Comment by tofran** [comment]
> Easier to maintain one check than every single adapter

I believe that there are other email properties that are not being checked in `mailer.ex` and what happens is the request fails gets refused by the third party.
I'm not that into the code, and I would have to recheck it to find where and what exactly.

> is_map_key was introduced in Elixir 1
Okay I see. Sorry I'm till very new to Elixir.
For now, I will leave it failing because it might be directly dependent on the solution for the `from`

**Comment by princemaple** [comment]
Hi, I fixed the `is_map_key` issue, added `cc`, `bcc`, `textContent` and `htmlContent`. Also added tags, thought that might be useful.

**Comment by princemaple** [comment]
Added a not so elegant workaround for `from`.

**Comment by princemaple** [comment]
I believe it's basically done. Please add tests and update readme.

**Comment by tofran** [comment]
@princemaple thank you. I will work on it next week

**Comment by princemaple** [comment]
ping

**Comment by princemaple** [comment]
BTW still need unit tests.

**Comment by tofran** [comment]
@princemaple yes of course.
I'm half thru writing them. But has been a painful task because theres a problem with the current bypass setup (basd on [sengrid tests](https://github.com/swoosh/swoosh/blob/528c638d5d0de643c1dac0993dc9487f365c17a4/lib/swoosh/adapters/sendgrid.ex#L66)):

Since we are doing assertions inside `Bypass.expect`:


```elixir
Bypass.expect_once(bypass, fn conn ->
  conn = parse(conn)

  body_params = %{
    "sender" => %{"email" => "tony.stark@example.com"},
    "to" => [%{"email" => "steve.rogers@example.com"}],
    "textContent" => "Hello",
    "subject" => "Hello, Avengers!",
    "template" => 42,
    "params" => %{
      "some_template_param" => "sample value",
      "another_one" => 99
    },
  }

  # (....)
end)
```

The error does not raise to the test.
Making the returning log look like this:

```
11:37:22.867 [error] #PID<0.333.0> running Bypass.Plug (connection #PID<0.332.0>, stream id 1) terminated
Server: localhost:43851 (http)
Request: POST /v3/smtp/email
** (exit) an exception was raised:
    ** (ExUnit.AssertionError) 

Assertion with == failed
code:  assert body_params == conn.body_params
left:  %{"params" => %{"another_one" => 99, "some_template_param" => "sample value"}, "sender" => %{"email" => "tony.stark@example.com"}, "subject" => "Hello, Avengers!", "template" => 42, "textContent" => "Hello", "to" => [%{"email" => "steve.rogers@example.com"}]}
right: %{"params" => %{"another_one" => 99, "sample_template_param" => "sample value"}, "sender" => %{"email" => "tony.stark@example.com"}, "subject" => "Hello, Avengers!", "templateId" => 42, "textContent" => "Hello", "to" => [%{"email" => "steve.rogers@example.com"}]}

        (ex_unit 1.11.3) lib/ex_unit/assertions.ex:397: ExUnit.Assertions.assert/2
        test/swoosh/adapters/sendinblue_test.exs:29: Swoosh.Adapters.SendinblueTest.assert_request_is_valid/2
        test/swoosh/adapters/sendinblue_test.exs:177: anonymous fn/1 in Swoosh.Adapters.SendinblueTest."test delivery/1 with template params returns :ok"/1
        (bypass 2.1.0) lib/bypass/plug.ex:14: Bypass.Plug.call/2
        (plug_cowboy 2.4.1) lib/plug/cowboy/handler.ex:12: Plug.Cowboy.Handler.init/2
        (cowboy 2.8.0) /Users/francisco/repos/swoosh/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /Users/francisco/repos/swoosh/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /Users/francisco/repos/swoosh/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


  1) test delivery/1 with template params returns :ok (Swoosh.Adapters.SendinblueTest)
     test/swoosh/adapters/sendinblue_test.exs:149
     Assertion with == failed
     code:  assert Sendinblue.deliver(email, config) == {:ok, %{id: "#{@example_message_id}"}}
     left:  {:error, {500, ""}}
     right: {:ok, %{id: "<42.11@relay.example.com>"}}
     stacktrace:
       test/swoosh/adapters/sendinblue_test.exs:181: (test)
```

as you can see ExUnit is outoputing

```
left:  {:error, {500, ""}}
right: {:ok, %{id: "<42.11@relay.example.com>"}}
```

But what should be 
```
left:  %{
          "params" => %{"another_one" => 99, "some_template_param" => "sample value"},
          "sender" => %{"email" => "tony.stark@example.com"},
          "subject" => "Hello, Avengers!",
          "textContent" => "Hello",
          "to" => [%{"email" => "steve.rogers@example.com"}],
          "template" => 42
        }
 right: %{
          "params" => %{"another_one" => 99, "sample_template_param" => "sample value"},
          "sender" => %{"email" => "tony.stark@example.com"},
          "subject" => "Hello, Avengers!",
          "textContent" => "Hello",
          "to" => [%{"email" => "steve.rogers@example.com"}],
          "templateId" => 42
        }
```

Obviously you can try to work with the log without the fancy format from ExUnit, but it is, as I said previously, super painful.

Do you know what is the best way to solve this? A simple solution that wouldn't change much is making Bypass raise.

**Comment by tofran** [comment]
Everything working.
image

Ready for review.
What do you think?

The issue from the previous comment persists, but I just worked with it.
Maybe I should open an issue to solve that.

**Comment by princemaple** [comment]
How Bypass handles it is not wrong. It's one of the correct ways it could be handled in. It's just unfortunate that it's not the way you wanted there in the scenario. You could add a mode to Bypass to not catch errors on "server" side.

I'll do a final pass soon and merge if no other issues. Thanks for the PR!

**Pull request merged**
