### PR TITLE
Use Attachment get_content

### PR DESCRIPTION
**Pull request by princemaple**
@mpran sorry missed this one

### CODE REVIEW

**Comment by mpran** [comment]
@princemaple nice catch. Sorry, should have checked it closer

**Comment by princemaple** [comment]
@mpran will you get a chance to test Swoosh master with some existing code for a few days?

**Comment by mpran** [comment]
@princemaple yup, I will update to point to master and let you know if everything looks good.

**Comment by princemaple** [comment]
Thanks a lot!

**Comment by princemaple** [comment]
Hi @mpran , if no issues have raised since, I will make a release sometime next week.

**Comment by mpran** [comment]
hi @princemaple I have been using it in prod for few days now and haven't seen any issues. Feel free to ping me if there are any reported problems with it. Thanks!

**Pull request merged**
