### PR TITLE
Add sparkpost

### LINKED ISSUE #103: Support sparkpost
https://developers.sparkpost.com/

I'll probably send a PR when I get some time.

### PR DESCRIPTION
**Pull request by princemaple**
- [x] tests
- [x] readme

cc @stevedomin 

closes #103

### CODE REVIEW

**Comment by princemaple** [comment]
I've tested locally and successfully sent emails via SparkPost.

**Comment by princemaple** [comment]
ping @stevedomin

**Comment by stevedomin** [comment]
@princemaple reviewing now!

**Comment by stevedomin** [comment]
Looks great, thanks so much for working on it!

**Comment by princemaple** [comment]
Thanks for merging. Any chance making a release for this sometime soon?

**Comment by stevedomin** [comment]
@princemaple 0.7 is out! Let me know if you run into any bugs.

**Pull request merged**
