### PR TITLE
allow empty content in sendgrid

### LINKED ISSUE #416: Sendgrid Adapter
On Sendgrid adapter, its present this code:

`defp prepare_body(email) do
    %{}
    |> prepare_from(email)
    |> prepare_personalizations(email)
    |> prepare_subject(email)
    |> prepare_content(email)
    |> prepare_attachments(email)
    |> prepare_reply_to(email)
    |> prepare_template_id(email)
    |> prepare_categories(email)
    |> prepare_asm(email)
    |> prepare_custom_headers(email)
    |> prepare_mail_settings(email)
  end`

And

`defp prepare_content(body, %{html_body: html, text_body: text}) do
    content =
      cond do
        html && text -> [%{type: "text/plain", value: text}, %{type: "text/html", value: html}]
        html -> [%{type: "text/html", value: html}]
        text -> [%{type: "text/plain", value: text}]
      end
    Map.put(body, :content, content)
  end`

But, if I use template_id functionality, the email content will be present into sendgrid, so, at moment, I wouldn't have a html_body or text_body to input on Map.
If I not put body on Email struct the lib return that error:

`(swoosh) lib/swoosh/adapters/sendgrid.ex:72: Swoosh.Adapters.Sendgrid.prepare_body/1
(swoosh) Swoosh.Adapters.Sendgrid.prepare_content/2
[error] ** (CondClauseError) no cond clause evaluated to a truthy value`

How I should use template_id functionality without broke the lib?

### PR DESCRIPTION
**Pull request by princemaple**
close #416 

@danielscosta please take a look

Meaningful changes are only https://github.com/swoosh/swoosh/pull/419/files#diff-6fd5df4a59b213f0014cda474e9e7511R147-R158

### CODE REVIEW

**Comment by danielscosta** [comment]
I tested this branch and works!
Thanks.

**Comment by princemaple** [comment]
Thanks for the confirmation!

**Comment by danielscosta** [comment]
@princemaple Could you create a new version of lib on hex?

**Comment by princemaple** [comment]
done

**Comment by danielscosta** [comment]
Thank you!

**Pull request merged**
