### PR TITLE
[feature] adds support to mandrill adapter for global merge vars and named templates

### PR DESCRIPTION
**Pull request by sescobb27**
closes https://github.com/swoosh/swoosh/issues/171

### CODE REVIEW

**Comment by princemaple** [comment]
Hey @sescobb27 thanks for reporting and congrats on the first time contribution!
I don't use mandrill, so I'll simply ping @stevedomin for you :)

**Comment by sescobb27** [comment]
:) thanks @princemaple, this is my first ever elixir contribution, I have just been working with elixir for 3 weeks, this is super exciting 🎉

**Comment by princemaple** [comment]
> this is my first ever elixir contribution

Wow 🎉 🎉 🎉 👍

**Comment by sescobb27** [comment]
Hi @stevedomin done :)

**Comment by stevedomin** [comment]
Perfect, thanks again @sescobb27!!

**Pull request merged**
