### PR TITLE
Allow smtp "MAIL FROM" to be different to "From" header

### PR DESCRIPTION
**Pull request by nicksanders**
For SMTP use the "Sender" header, when it is set, as the "MAIL FROM" instead of the From address.

### CODE REVIEW

**Comment by stevedomin** [comment]
hi @nicksanders 

Thanks for the PR.

While we are at it can we make it so that we fully respect the spec. I think you need to use the `Return-Path` header first if there's one. What do you think of something like:

```elixir
email.headers["Return-Path"] || email.headers["Sender"] || elem(email.from, 1)
```

**Comment by nicksanders** [comment]
Your code looks a lot cleaner than mine but I think the client shouldn't set the return path so we shouldn't use it?

https://tools.ietf.org/html/rfc5321#section-4.4
https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php line 92

**Comment by stevedomin** [comment]
Yep, you're correct, my apologies.

Can you update the code with the simpler version? And then I'll merge.

**Comment by stevedomin** [comment]
Thanks a lot @nicksanders!!

**Pull request merged**
