### PR TITLE
encode map and list only

### LINKED ISSUE #417: mailgun, string variables should not be jason encoded
When using `prepare_custom_vars` a simple string should not be json encoded.

### PR DESCRIPTION
**Pull request by steffenix**
closes #417

### CODE REVIEW

**Comment by princemaple** [comment]
Just to confirm, do numbers, booleans and null work without encoding?

**Comment by princemaple** [comment]
Thanks for bringing it up and sending the PR :)

**Comment by steffenix** [comment]
I will try.

**Comment by princemaple** [comment]
@steffenix thanks a lot.

**Comment by steffenix** [comment]
boolean, numbers and null all are ok.

**Comment by princemaple** [comment]
Fantastic, cheers.

**Pull request merged**
