### PR TITLE
Mailjet adapter

### PR DESCRIPTION
**Pull request by denispeplin**
Not 100% ready, some preparations are disabled, but already usable.

I would leave it in open pull requests in case someone needs it.

### CODE REVIEW

**Comment by princemaple** [comment]
Hi @denispeplin , I added some changes based on your code. I'd appreciate if you can test the code I added and let me know if everything works.

**Comment by denispeplin** [comment]
Looks like it works, but I'll also test it on production next Monday.

**Comment by denispeplin** [comment]
Works fine, thanks!
I'm using it like this:

```elixir
    new()
    |> to({name, email})
    |> bcc({@bcc_name, @bcc_email})
    |> from({"Sender", sender_email()})
    |> subject("Statistics")
    |> html_body("<h1>Statistics</h1>")
    |> text_body("Statistics\n")
    |> attachment(attachment)
```

And everything I'm using works.

**Comment by princemaple** [comment]
Great, thanks for reporting back. Inline attachments didn't work for me last time I tested. Well, it got attached, but not inlined correctly. Not sure if it's the code or the service. I'll find some time to test again this weekend. The rest seems to work well. We will also need some tests if we want to merge this into master.

**Comment by princemaple** [comment]
Still couldn't get inline attachments to work. Mailjet doesn't seem to do what its documentation says.

**Comment by denispeplin** [comment]
But this is not a problem for many users. For me for example :)

**Comment by princemaple** [comment]
I don't mind merging it in without inline attachments working, as long as we put in a comment.

We still need tests though.

**Comment by panmichal** [comment]
I'm working on tests for the adapter. Would you prefer to get a new PR here or should I open a PR for your fork @denispeplin ?

**Comment by princemaple** [comment]
Hi @panmichal you can open a PR towards mailjet branch of this repo.

**Comment by panmichal** [comment]
Here it is: https://github.com/swoosh/swoosh/pull/366

**Comment by denispeplin** [comment]
@panmichal, do whatever is easier for you, I don't mind.

**Pull request closed without merging**
