### PR TITLE
Add dkim support to smtp adapter

### PR DESCRIPTION
**Pull request by nicksanders**
dkim config can be added to config or email.provider_options or both, dkim config in email.provider_options overrides the one in the config.

### CODE REVIEW

**Comment by stevedomin** [comment]
@nicksanders do you have a use-case for overriding the DKIM options on the per-email basis? If not I'd be quite keen on keeping it simple for now.

**Comment by nicksanders** [comment]
@stevedomin That's fine, I wanted the ability to use different dkim configs depending on the sender domain but I can update the config on deliver. I have also added dkim support to sendmail.

**Comment by stevedomin** [comment]
Thank you so much @nicksanders!!

As a heads up, I might end up extracting the common functionalities from SMTP and Sendmail in a separate module. Haven't figured out where it should live yet.

**Comment by nicksanders** [comment]
Yeah, I had thought that as well, something like RawEmail

**Comment by barisbalic** [comment]
:+1: on the extraction, documenting my opinion even though we've talked about it :D

**Pull request merged**
