### PR TITLE
fix: download attachment with the filename

### PR DESCRIPTION
**Pull request by RETFU**
Use the original file name of the attachment when downloading it instead of 1, 2, 3...

image

### CODE REVIEW

**Comment by princemaple** [comment]
oops sorry about being late on this one

**Comment by princemaple** [comment]
Looks good!

**Comment by RETFU** [comment]
> oops sorry about being late on this one

No big deal, thx for your time.

**Comment by princemaple** [comment]
Cheers. It's out in 1.17.2

**Pull request merged**
