### PR TITLE
Allow overriding delivery functions

### PR DESCRIPTION
**Pull request by jakub-gonet**
Sometimes, it's really convenient to do some preprocessing of an email (returning an error when recipient list is empty, inlining CSS, etc) that is adapter independent.

I'm open to suggestions how to improve telemetry as only base implementation is covered by it.

### CODE REVIEW

**Comment by princemaple** [comment]
Thanks for the PR!

I'm in general not in favor of unnecessary overrides and hooks. I think preprocess can be done with a wrapper function, e.g. `safe_deliver(...)` that wraps existing function. Inlining CSS sounds more like a rendering problem which should be solved before it is put into the email, at the template (engine) level.

I'm not strongly against making them overridable though. 🤔

**Comment by princemaple** [comment]
Actually yeah I don't want to make them overridable. This would cause more magic and make things confusing and hard to search for. I think I much prefer keeping it as is and have users write wrapper functions - so that later on when they have doubts about what their custom `deliver_*` or `*_deliver` does, they get the correct search result.

💜 for the PR though!

**Comment by jakub-gonet** [comment]
Sure, thanks for feedback!

**Comment by jakub-gonet** [comment]
One another though I had this morning about this: I felt like doing it, because Swoosh injects functions in module scoped to my project.

If I use a library, I expect all calls to it directly to have same behavior but any call to `MyProject.Library` is in uncharted territory and if I had a reason to use this instead of library directly then I probably added some additional logic.

That being said, I'm fine with this PR being rejected.

**Comment by princemaple** [comment]
I looked at how `Ecto` does `Repo`. Seeing that `all` and `one` and the rest aren't overridable, I decided that `Mailer` shouldn't make `deliver` overridable either. One could argue they'd want to override `all` to make a cached version, but again, one could always just make a `cached_all`.

My own opinion is really just code discoverability. Code should be easily searchable and app code should not be confused with library code.

**Comment by adamu** [comment]
I think it might be better if instead of injecting the `deliver` functions from `use Swoosh.Mailer`, they were actually defined on the Swoosh.Mailer module (or a behaviour) that library users could choose the call as they like. For example, in the current version, the telemetry logic is [only applied by default when using the injected functions](https://github.com/swoosh/swoosh/blob/4a59f125c014edaaf9f23de43f76db1e8cb3b691/lib/swoosh/mailer.ex#L131-L133).

**Comment by princemaple** [comment]
The major reason for code injection is to read the specific configuration for the mailer, through the module name.

However I agree that the injected code can be further reduced, as noted in https://github.com/swoosh/swoosh/issues/556

Maybe when we get to a point where the injected code is reduced to the bare minimum, and `use Swoosh.Mailer` becomes a pure convenience like `use GenServer`, i.e. contains no code with logic, we can make the deliver functions overridable.

**Pull request closed without merging**
