### PR TITLE
handlebar substitutions with dynamic_template_data

### PR DESCRIPTION
**Pull request by steffenix**

### CODE REVIEW

**Comment by princemaple** [comment]
Thanks @steffenix , could you rebase to the latest master (github isn't offering to merge master into this branch, maybe there is a big diff?) and provide a link to the documentation of the added feature?

**Comment by princemaple** [comment]
On this page https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html I don't see anything about `dynamic_template_data`. I think the feature you are trying to implement is already there? `substitutions`

**Comment by steffenix** [comment]
I will see with @chakming if he can update is branch. We were looking at https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/

**Comment by princemaple** [comment]
What's the difference between `substitutions` and `dynamic_template_data`?

**Comment by steffenix** [comment]
we tried substitutions and it was not working with  transactional templates.

**Comment by princemaple** [comment]
Yeah it's so weird. One version of their docs I found uses `substitutions` and I also found another version that uses `dynamic_template_data`. Since I don't use SendGrid myself, I have no idea which one is correct, or if both are needed for different situations.

**Comment by steffenix** [comment]
We were confused too.

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh/pull/276 isn't this commit already merged in this PR?

**Pull request closed without merging**
